{% set name = "anyconfig" %}
{% set version = "0.9.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 621b0b5f08efd2e375596b50f79943200d90f0397fed55cf0d2f5f484e005e9d

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  entry_points:
    - anyconfig_cli = anyconfig.cli:main
requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - setuptools
    - python

test:
  imports:
    - anyconfig

about:
  home: https://github.com/ssato/python-anyconfig
  license: MIT
  license_family: MIT
  license_file: LICENSE.MIT
  summary: 'Library provides common APIs to load and dump configuration files in various formats'
  description: |
    python-anyconfig is a python library provides common APIs to load and dump
    configuration files in various formats with some useful features such as
    contents merge, templates, query, schema validation and generation support.

    - Home: https://github.com/ssato/python-anyconfig
    - Author: Satoru SATOH <satoru.satoh@gmail.com>
    - License: MIT
    - Document: http://python-anyconfig.readthedocs.org/en/latest/
    - Download: PyPI (https://pypi.python.org/pypi/anyconfig) or Copr RPM repos ( https://copr.fedoraproject.org/coprs/ssato/python-anyconfig/)
  doc_url: https://python-anyconfig.readthedocs.io/en/latest/
  dev_url: https://github.com/ssato/python-anyconfig

extra:
  recipe-maintainers:
    - knightdave
