{% set name = "anyconfig" %}
{% set version = "0.13.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 03ff2e1762af388fbbbed1c1ab7f9f1ec006a91da7db3a68b963da6e7795d2ac

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation  -vv
  entry_points:
    - anyconfig_cli = anyconfig.cli:main
requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - setuptools
    - Jinja2
    - PyYAML
    - jmespath
    - jsonschema
    - ruamel.yaml
    - simplejson
    - toml
test:
  source_files:
    - tests
  imports:
    - anyconfig
    - anyconfig.singleton
  commands:
    - pip check
    - anyconfig_cli --help
    - pytest -v tests
  requires:
    - pytest
    - pip


about:
  home: https://github.com/ssato/python-anyconfig
  license: MIT
  license_family: MIT
  license_file: LICENSE.MIT
  summary: Library provides common APIs to load and dump configuration files in various formats
  description: |
    python-anyconfig is a python library provides common APIs to load and dump
    configuration files in various formats with some useful features such as
    contents merge, templates, query, schema validation and generation support.

    - Home: https://github.com/ssato/python-anyconfig
    - Author: Satoru SATOH <satoru.satoh@gmail.com>
    - License: MIT
    - Document: http://python-anyconfig.readthedocs.org/en/latest/
    - Download: PyPI (https://pypi.python.org/pypi/anyconfig) or Copr RPM repos ( https://copr.fedoraproject.org/coprs/ssato/python-anyconfig/)
  doc_url: https://python-anyconfig.readthedocs.io/
  dev_url: https://github.com/ssato/python-anyconfig

extra:
  recipe-maintainers:
    - knightdave
