{% set name = "anyconfig" %}
{% set version = "0.11.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 050dcade09799cd19c9b1f834e6df710ef824b388e6bb0af8c77be39b158b011

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - anyconfig_cli = anyconfig.cli:main
requirements:
  host:
    - python >=3.6
    - pip
    - setuptools
  run:
    - setuptools
    - python >=3.6

test:
  imports:
    - anyconfig
  commands:
    - pip check
    - anyconfig_cli --help
  requires:
    - pip

about:
  home: https://github.com/ssato/python-anyconfig
  license: MIT
  license_family: MIT
  license_file: LICENSE.MIT
  summary: Library provides common APIs to load and dump configuration files in various formats
  description: |
    python-anyconfig is a python library provides common APIs to load and dump
    configuration files in various formats with some useful features such as
    contents merge, templates, query, schema validation and generation support.

    - Home: https://github.com/ssato/python-anyconfig
    - Author: Satoru SATOH <satoru.satoh@gmail.com>
    - License: MIT
    - Document: http://python-anyconfig.readthedocs.org/en/latest/
    - Download: PyPI (https://pypi.python.org/pypi/anyconfig) or Copr RPM repos ( https://copr.fedoraproject.org/coprs/ssato/python-anyconfig/)
  doc_url: https://python-anyconfig.readthedocs.io/en/latest/
  dev_url: https://github.com/ssato/python-anyconfig

extra:
  recipe-maintainers:
    - knightdave
