travis:
  secure:
    BINSTAR_TOKEN: SV/XgdAW+iYZC0vyqtff4MrhU2u/MPx6vf71p+zsbInMUMiPsJcxOLcH3W66aZx5wh1MRKyPt0/yhFrbfCa0yTuZeuY4GULW7Nb5jyDbRMN1DmG4XTh/b2Aym7W5AfsS0EHLudoQ+dffBMwdOv1RvDvjGK8bDPXB9N6LrYzB/6MXLznoVhErsYp7B22TcmaYCOWj9F144dRqTfy5uU52fZSCs8GJF2K/Bsk4T9PB8X/Q4BJpIR9V7TyeVByKxWou+GG5FQJdbS1okB1HgcvNxKuLx4MuQKlpYk7++eI87eCyZg5yhQJXxK8kI6nVURIX5/jtT9h9moCWvy+1WW8x+AZ2YCE1cRTkvCyQOlfMmLTB0Z3yZBNfjuJz+40fbD1oBciBRFDiLD2jq5D8qZkNux5wMbtC6F7xUGfUpwS2v2zEnhZUYTsxLGjuv+ZYsZ/TreV78tewVmjuCOllfZMAm/iAj+xS8jYi55Xq2yDAKCz/5hXAKdIDhZgw+VHULU0nZIGTsFoCei+gNNuUwWUwyULzOE1TyOL7RZWPEuJ1c7XbC5IO9Irgec5jl4ZWIzNqrTuRbBof5aqxgN7llw7yYAPfD5y4YCY6tZXO1hRbJyicIxl+7pHO/f4XEhwKqYNK5JpVn8GH3g4MmOBu6Aqku3brlehh1h2yL2M++o0Pjuc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
